### ISSUE TITLE
List of resources

### ISSUE THREAD

**Issue by manasvil** [meagdoh/data-and-friends#37]
In your [Medium article](https://medium.com/read-write-participate/achieving-data-literacy-through-fun-and-games-15375156ebd5) you talk about finding resources such as https://databasic.io/en/culture/ while doing research for this project. Is there a list of the resources you found? That alone is a great starting point for someone learning about Digital Literacy.

**Comment by meagdoh** [comment]
Hey @manasvil We have a short running list here: https://github.com/meagdoh/data-and-friends/issues/1 -- please feel free to add any we might have missed
