### ISSUE TITLE
Identify and document similar game design projects

### ISSUE THREAD

**Issue by meagdoh** [meagdoh/data-and-friends#6]
We are always looking for inspiration from existing game designs!
Feel free to leave any games and their designs in the comments section on this issue. 
In the comment, please include,

Organization/Project Name:
Link to Work:
Game Mechanics used:

**Comment by bvhme** [comment]
Organization/Project Name: No Man's Land by Janna Ullrich
Link to Work: http://jannaullrich.de/ (actual site of project down, I've emailed Janna for more documentation)
Game Mechanics used: Board game

> 'No Man's Land' is a board game that aims to expose the absurd practices of today's immigration industry. It embodies the bureaucratic prison in which refugees get stuck after they have fled their country but can't enter another.
